; generated by SuperSlicer 2.4 on 2022-07-09 at 18:05:05 UTC

; object:{"name":"tapered_cube","id":"tapered_cube.stl id:0 copy 0","object_center":[142.878680,132.878681,0.000000],"boundingbox_center":[142.878680,132.878681,5.000000],"boundingbox_size":[15.000000,15.000000,10.000000]}
; object:{"name":"tapered_cube","id":"tapered_cube.stl id:0 copy 1","object_center":[157.121321,147.121320,0.000000],"boundingbox_center":[157.121321,147.121320,5.000000],"boundingbox_size":[15.000000,15.000000,10.000000]}
; plater:{"center":[150.000000,140.000000,0.000000],"boundingbox_center":[150.000000,140.000000,5.000000],"boundingbox_size":[29.242641,29.242639,10.000000]}

;TYPE:Custom
print_start EXTRUDER=240 BED=110 CHAMBER=40 MATERIAL=ABS

; SET_RETRACTION RETRACT_LENGTH=0.75 RETRACT_SPEED=50 UNRETRACT_SPEED=30 UNRETRACT_EXTRA_LENGTH=0
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
SET_PRESSURE_ADVANCE ADVANCE=0.0535
M109 S240 ; set temperature and wait for it to be reached
M190 S110 ; set bed temperature and wait for it to be reached
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2

G1 Z0.2 F18000
;AFTER_LAYER_CHANGE
;0.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z0.6 F18000
; printing object tapered_cube.stl id:0 copy 0
M204 S2000
G1 X136.326 Y131.226
G1 Z0.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.56
G1 F900
G1 X144.532 Y131.226 E0.32988
G1 X144.532 Y139.432 E0.32988
G1 X136.326 Y139.432 E0.32988
G1 X136.326 Y131.286 E0.32747
G1 X135.809 Y130.709 F18000
;TYPE:External perimeter
G1 F900
G1 X145.049 Y130.709 E0.37145
G1 X145.049 Y139.949 E0.37145
G1 X135.809 Y139.949 E0.37145
G1 X135.809 Y130.769 E0.36904
;WIPE_START
M204 S5000
G1 X136.155 Y130.909 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z0.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X146.45 Y141.308
; decel to extrusion
M204 S2000
G1 X150.568 Y145.468
; end travel
G1 Z0.2
G1 E0.75 F1800
;TYPE:Internal perimeter
G1 F900
G1 X158.774 Y145.468 E0.32988
G1 X158.774 Y153.674 E0.32988
G1 X150.568 Y153.674 E0.32988
G1 X150.568 Y145.528 E0.32747
G1 X150.051 Y144.951 F18000
;TYPE:External perimeter
G1 F900
G1 X159.291 Y144.951 E0.37145
G1 X159.291 Y154.191 E0.37145
G1 X150.051 Y154.191 E0.37145
G1 X150.051 Y145.011 E0.36904
;WIPE_START
M204 S5000
G1 X150.398 Y145.151 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z0.4 F18000
;AFTER_LAYER_CHANGE
;0.4

TIMELAPSE_TAKE_FRAME
G92 E0
M104 S235 ; set temperature
M140 S105 ; set bed temperature
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z0.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X147.75 Y142.477
; decel to extrusion
M204 S4500
G1 X144.952 Y139.652
; end travel
G1 Z0.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.106 Y139.652 E0.27308
G1 X136.106 Y130.806 E0.27308
G1 X144.952 Y130.806 E0.27308
G1 X144.952 Y139.592 E0.27123
G1 X145.327 Y140.029 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X135.729 Y140.029 E0.26645
G1 X135.729 Y130.431 E0.26645
;TYPE:Overhang perimeter
G1 F2400
M204 S3000
G1 X145.329 Y130.429 E0.26651
G1 X145.329 Y139.969 E0.26484
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
M204 S5000
G1 Z0.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X147.774 Y142.444
; decel to extrusion
M204 S4500
G1 X150.348 Y145.048
; end travel
G1 Z0.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.194 Y145.048 E0.27308
G1 X159.194 Y153.894 E0.27308
G1 X150.348 Y153.894 E0.27308
G1 X150.348 Y145.108 E0.27123
M204 S3000
G1 X149.971 Y144.671 F18000
;TYPE:Overhang perimeter
;WIDTH:0.4
G1 F2400
G1 X159.571 Y144.671 E0.26651
G1 X159.569 Y154.271 E0.26651
;TYPE:External perimeter
G1 F900
M204 S4500
G1 X149.971 Y154.271 E0.26645
G1 X149.971 Y144.731 E0.26484
;WIPE_START
M204 S5000
G1 X150.318 Y144.871 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z0.6 F18000
;AFTER_LAYER_CHANGE
;0.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z1 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X147.678 Y142.205
; decel to extrusion
M204 S4500
G1 X145.052 Y139.552
; end travel
G1 Z0.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.206 Y139.552 E0.27308
G1 X136.206 Y130.706 E0.27308
G1 X145.052 Y130.706 E0.27308
G1 X145.052 Y139.492 E0.27123
G1 X145.429 Y139.929 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X135.829 Y139.929 E0.26651
G1 X135.829 Y130.329 E0.26651
G1 X145.429 Y130.329 E0.26651
G1 X145.429 Y139.869 E0.26484
;WIPE_START
M204 S5000
G1 X145.082 Y139.729 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z1 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X147.772 Y142.345
; decel to extrusion
M204 S4500
G1 X150.448 Y144.948
; end travel
G1 Z0.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.294 Y144.948 E0.27308
G1 X159.294 Y153.794 E0.27308
G1 X150.448 Y153.794 E0.27308
G1 X150.448 Y145.008 E0.27123
G1 X150.071 Y144.571 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X159.671 Y144.571 E0.26651
G1 X159.671 Y154.171 E0.26651
G1 X150.071 Y154.171 E0.26651
G1 X150.071 Y144.631 E0.26484
;WIPE_START
M204 S5000
G1 X150.418 Y144.771 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z0.8 F18000
;AFTER_LAYER_CHANGE
;0.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z1.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X147.778 Y142.105
; decel to extrusion
M204 S4500
G1 X145.152 Y139.452
; end travel
G1 Z0.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.306 Y139.452 E0.27308
G1 X136.306 Y130.606 E0.27308
G1 X145.152 Y130.606 E0.27308
G1 X145.152 Y139.392 E0.27123
G1 X145.529 Y139.829 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X135.929 Y139.829 E0.26651
G1 X135.929 Y130.229 E0.26651
G1 X145.529 Y130.229 E0.26651
G1 X145.529 Y139.769 E0.26484
;WIPE_START
M204 S5000
G1 X145.182 Y139.629 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z1.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X147.872 Y142.245
; decel to extrusion
M204 S4500
G1 X150.548 Y144.848
; end travel
G1 Z0.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.394 Y144.848 E0.27308
G1 X159.394 Y153.694 E0.27308
G1 X150.548 Y153.694 E0.27308
G1 X150.548 Y144.908 E0.27123
G1 X150.171 Y144.471 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X159.771 Y144.471 E0.26651
G1 X159.771 Y154.071 E0.26651
G1 X150.171 Y154.071 E0.26651
G1 X150.171 Y144.531 E0.26484
;WIPE_START
M204 S5000
G1 X150.518 Y144.671 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z1 F18000
;AFTER_LAYER_CHANGE
;1

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z1.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X147.878 Y142.005
; decel to extrusion
M204 S4500
G1 X145.252 Y139.352
; end travel
G1 Z1
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.406 Y139.352 E0.27308
G1 X136.406 Y130.506 E0.27308
G1 X145.252 Y130.506 E0.27308
G1 X145.252 Y139.292 E0.27123
G1 X145.629 Y139.729 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.029 Y139.729 E0.26651
G1 X136.029 Y130.129 E0.26651
G1 X145.629 Y130.129 E0.26651
G1 X145.629 Y139.669 E0.26484
;WIPE_START
M204 S5000
G1 X145.282 Y139.529 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z1.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X147.972 Y142.145
; decel to extrusion
M204 S4500
G1 X150.648 Y144.748
; end travel
G1 Z1
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.494 Y144.748 E0.27308
G1 X159.494 Y153.594 E0.27308
G1 X150.648 Y153.594 E0.27308
G1 X150.648 Y144.808 E0.27123
G1 X150.271 Y144.371 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X159.871 Y144.371 E0.26651
G1 X159.871 Y153.971 E0.26651
G1 X150.271 Y153.971 E0.26651
G1 X150.271 Y144.431 E0.26484
;WIPE_START
M204 S5000
G1 X150.618 Y144.571 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
M106 S153
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z1.2 F18000
;AFTER_LAYER_CHANGE
;1.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z1.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X147.978 Y141.905
; decel to extrusion
M204 S4500
G1 X145.352 Y139.252
; end travel
G1 Z1.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.506 Y139.252 E0.27308
G1 X136.506 Y130.406 E0.27308
G1 X145.352 Y130.406 E0.27308
G1 X145.352 Y139.192 E0.27123
G1 X145.729 Y139.629 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.129 Y139.629 E0.26651
G1 X136.129 Y130.029 E0.26651
G1 X145.729 Y130.029 E0.26651
G1 X145.729 Y139.569 E0.26484
;WIPE_START
M204 S5000
G1 X145.382 Y139.429 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z1.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.072 Y142.045
; decel to extrusion
M204 S4500
G1 X150.748 Y144.648
; end travel
G1 Z1.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.594 Y144.648 E0.27308
G1 X159.594 Y153.494 E0.27308
G1 X150.748 Y153.494 E0.27308
G1 X150.748 Y144.708 E0.27123
G1 X150.371 Y144.271 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X159.971 Y144.271 E0.26651
G1 X159.971 Y153.871 E0.26651
G1 X150.371 Y153.871 E0.26651
G1 X150.371 Y144.331 E0.26484
;WIPE_START
M204 S5000
G1 X150.718 Y144.471 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z1.4 F18000
;AFTER_LAYER_CHANGE
;1.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z1.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.078 Y141.805
; decel to extrusion
M204 S4500
G1 X145.452 Y139.152
; end travel
G1 Z1.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.606 Y139.152 E0.27308
G1 X136.606 Y130.306 E0.27308
G1 X145.452 Y130.306 E0.27308
G1 X145.452 Y139.092 E0.27123
G1 X145.829 Y139.529 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.229 Y139.529 E0.26651
G1 X136.229 Y129.929 E0.26651
G1 X145.829 Y129.929 E0.26651
G1 X145.829 Y139.469 E0.26484
;WIPE_START
M204 S5000
G1 X145.482 Y139.329 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z1.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.172 Y141.945
; decel to extrusion
M204 S4500
G1 X150.848 Y144.548
; end travel
G1 Z1.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.694 Y144.548 E0.27308
G1 X159.694 Y153.394 E0.27308
G1 X150.848 Y153.394 E0.27308
G1 X150.848 Y144.608 E0.27123
G1 X150.471 Y144.171 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.071 Y144.171 E0.26651
G1 X160.071 Y153.771 E0.26651
G1 X150.471 Y153.771 E0.26651
G1 X150.471 Y144.231 E0.26484
;WIPE_START
M204 S5000
G1 X150.818 Y144.371 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z1.6 F18000
;AFTER_LAYER_CHANGE
;1.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.178 Y141.705
; decel to extrusion
M204 S4500
G1 X145.552 Y139.052
; end travel
G1 Z1.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.706 Y139.052 E0.27308
G1 X136.706 Y130.206 E0.27308
G1 X145.552 Y130.206 E0.27308
G1 X145.552 Y138.992 E0.27123
G1 X145.929 Y139.429 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.329 Y139.429 E0.26651
G1 X136.329 Y129.829 E0.26651
G1 X145.929 Y129.829 E0.26651
G1 X145.929 Y139.369 E0.26484
;WIPE_START
M204 S5000
G1 X145.582 Y139.229 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.272 Y141.845
; decel to extrusion
M204 S4500
G1 X150.948 Y144.448
; end travel
G1 Z1.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.794 Y144.448 E0.27308
G1 X159.794 Y153.294 E0.27308
G1 X150.948 Y153.294 E0.27308
G1 X150.948 Y144.508 E0.27123
G1 X150.571 Y144.071 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.171 Y144.071 E0.26651
G1 X160.171 Y153.671 E0.26651
G1 X150.571 Y153.671 E0.26651
G1 X150.571 Y144.131 E0.26484
;WIPE_START
M204 S5000
G1 X150.918 Y144.271 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z1.8 F18000
;AFTER_LAYER_CHANGE
;1.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z2.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.278 Y141.605
; decel to extrusion
M204 S4500
G1 X145.652 Y138.952
; end travel
G1 Z1.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.806 Y138.952 E0.27308
G1 X136.806 Y130.106 E0.27308
G1 X145.652 Y130.106 E0.27308
G1 X145.652 Y138.892 E0.27123
G1 X146.029 Y139.329 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.429 Y139.329 E0.26651
G1 X136.429 Y129.729 E0.26651
G1 X146.029 Y129.729 E0.26651
G1 X146.029 Y139.269 E0.26484
;WIPE_START
M204 S5000
G1 X145.682 Y139.129 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z2.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.372 Y141.745
; decel to extrusion
M204 S4500
G1 X151.048 Y144.348
; end travel
G1 Z1.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.894 Y144.348 E0.27308
G1 X159.894 Y153.194 E0.27308
G1 X151.048 Y153.194 E0.27308
G1 X151.048 Y144.408 E0.27123
G1 X150.671 Y143.971 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.271 Y143.971 E0.26651
G1 X160.271 Y153.571 E0.26651
G1 X150.671 Y153.571 E0.26651
G1 X150.671 Y144.031 E0.26484
;WIPE_START
M204 S5000
G1 X151.018 Y144.171 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z2 F18000
;AFTER_LAYER_CHANGE
;2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z2.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.378 Y141.505
; decel to extrusion
M204 S4500
G1 X145.752 Y138.852
; end travel
G1 Z2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X136.906 Y138.852 E0.27308
G1 X136.906 Y130.006 E0.27308
G1 X145.752 Y130.006 E0.27308
G1 X145.752 Y138.792 E0.27123
G1 X146.129 Y139.229 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.529 Y139.229 E0.26651
G1 X136.529 Y129.629 E0.26651
G1 X146.129 Y129.629 E0.26651
G1 X146.129 Y139.169 E0.26484
;WIPE_START
M204 S5000
G1 X145.782 Y139.029 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z2.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.472 Y141.645
; decel to extrusion
M204 S4500
G1 X151.148 Y144.248
; end travel
G1 Z2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X159.994 Y144.248 E0.27308
G1 X159.994 Y153.094 E0.27308
G1 X151.148 Y153.094 E0.27308
G1 X151.148 Y144.308 E0.27123
G1 X150.771 Y143.871 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.371 Y143.871 E0.26651
G1 X160.371 Y153.471 E0.26651
G1 X150.771 Y153.471 E0.26651
G1 X150.771 Y143.931 E0.26484
;WIPE_START
M204 S5000
G1 X151.118 Y144.071 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z2.2 F18000
;AFTER_LAYER_CHANGE
;2.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z2.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.478 Y141.405
; decel to extrusion
M204 S4500
G1 X145.852 Y138.752
; end travel
G1 Z2.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.006 Y138.752 E0.27308
G1 X137.006 Y129.906 E0.27308
G1 X145.852 Y129.906 E0.27308
G1 X145.852 Y138.692 E0.27123
G1 X146.229 Y139.129 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.629 Y139.129 E0.26651
G1 X136.629 Y129.529 E0.26651
G1 X146.229 Y129.529 E0.26651
G1 X146.229 Y139.069 E0.26484
;WIPE_START
M204 S5000
G1 X145.882 Y138.929 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z2.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.572 Y141.545
; decel to extrusion
M204 S4500
G1 X151.248 Y144.148
; end travel
G1 Z2.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.094 Y144.148 E0.27308
G1 X160.094 Y152.994 E0.27308
G1 X151.248 Y152.994 E0.27308
G1 X151.248 Y144.208 E0.27123
G1 X150.871 Y143.771 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.471 Y143.771 E0.26651
G1 X160.471 Y153.371 E0.26651
G1 X150.871 Y153.371 E0.26651
G1 X150.871 Y143.831 E0.26484
;WIPE_START
M204 S5000
G1 X151.218 Y143.971 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z2.4 F18000
;AFTER_LAYER_CHANGE
;2.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z2.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.578 Y141.305
; decel to extrusion
M204 S4500
G1 X145.952 Y138.652
; end travel
G1 Z2.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.106 Y138.652 E0.27308
G1 X137.106 Y129.806 E0.27308
G1 X145.952 Y129.806 E0.27308
G1 X145.952 Y138.592 E0.27123
G1 X146.329 Y139.029 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.729 Y139.029 E0.26651
G1 X136.729 Y129.429 E0.26651
G1 X146.329 Y129.429 E0.26651
G1 X146.329 Y138.969 E0.26484
;WIPE_START
M204 S5000
G1 X145.982 Y138.829 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z2.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.672 Y141.445
; decel to extrusion
M204 S4500
G1 X151.348 Y144.048
; end travel
G1 Z2.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.194 Y144.048 E0.27308
G1 X160.194 Y152.894 E0.27308
G1 X151.348 Y152.894 E0.27308
G1 X151.348 Y144.108 E0.27123
G1 X150.971 Y143.671 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.571 Y143.671 E0.26651
G1 X160.571 Y153.271 E0.26651
G1 X150.971 Y153.271 E0.26651
G1 X150.971 Y143.731 E0.26484
;WIPE_START
M204 S5000
G1 X151.318 Y143.871 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z2.6 F18000
;AFTER_LAYER_CHANGE
;2.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z3 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.678 Y141.205
; decel to extrusion
M204 S4500
G1 X146.052 Y138.552
; end travel
G1 Z2.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.206 Y138.552 E0.27308
G1 X137.206 Y129.706 E0.27308
G1 X146.052 Y129.706 E0.27308
G1 X146.052 Y138.492 E0.27123
G1 X146.429 Y138.929 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.829 Y138.929 E0.26651
G1 X136.829 Y129.329 E0.26651
G1 X146.429 Y129.329 E0.26651
G1 X146.429 Y138.869 E0.26484
;WIPE_START
M204 S5000
G1 X146.082 Y138.729 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z3 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.772 Y141.345
; decel to extrusion
M204 S4500
G1 X151.448 Y143.948
; end travel
G1 Z2.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.294 Y143.948 E0.27308
G1 X160.294 Y152.794 E0.27308
G1 X151.448 Y152.794 E0.27308
G1 X151.448 Y144.008 E0.27123
G1 X151.071 Y143.571 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.671 Y143.571 E0.26651
G1 X160.671 Y153.171 E0.26651
G1 X151.071 Y153.171 E0.26651
G1 X151.071 Y143.631 E0.26484
;WIPE_START
M204 S5000
G1 X151.418 Y143.771 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z2.8 F18000
;AFTER_LAYER_CHANGE
;2.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z3.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.778 Y141.105
; decel to extrusion
M204 S4500
G1 X146.152 Y138.452
; end travel
G1 Z2.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.306 Y138.452 E0.27308
G1 X137.306 Y129.606 E0.27308
G1 X146.152 Y129.606 E0.27308
G1 X146.152 Y138.392 E0.27123
G1 X146.529 Y138.829 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X136.929 Y138.829 E0.26651
G1 X136.929 Y129.229 E0.26651
G1 X146.529 Y129.229 E0.26651
G1 X146.529 Y138.769 E0.26484
;WIPE_START
M204 S5000
G1 X146.182 Y138.629 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z3.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.872 Y141.245
; decel to extrusion
M204 S4500
G1 X151.548 Y143.848
; end travel
G1 Z2.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.394 Y143.848 E0.27308
G1 X160.394 Y152.694 E0.27308
G1 X151.548 Y152.694 E0.27308
G1 X151.548 Y143.908 E0.27123
G1 X151.171 Y143.471 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.771 Y143.471 E0.26651
G1 X160.771 Y153.071 E0.26651
G1 X151.171 Y153.071 E0.26651
G1 X151.171 Y143.531 E0.26484
;WIPE_START
M204 S5000
G1 X151.518 Y143.671 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z3 F18000
;AFTER_LAYER_CHANGE
;3

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z3.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.878 Y141.005
; decel to extrusion
M204 S4500
G1 X146.252 Y138.352
; end travel
G1 Z3
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.406 Y138.352 E0.27308
G1 X137.406 Y129.506 E0.27308
G1 X146.252 Y129.506 E0.27308
G1 X146.252 Y138.292 E0.27123
G1 X146.629 Y138.729 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.029 Y138.729 E0.26651
G1 X137.029 Y129.129 E0.26651
G1 X146.629 Y129.129 E0.26651
G1 X146.629 Y138.669 E0.26484
;WIPE_START
M204 S5000
G1 X146.282 Y138.529 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z3.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X148.972 Y141.145
; decel to extrusion
M204 S4500
G1 X151.648 Y143.748
; end travel
G1 Z3
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.494 Y143.748 E0.27308
G1 X160.494 Y152.594 E0.27308
G1 X151.648 Y152.594 E0.27308
G1 X151.648 Y143.808 E0.27123
G1 X151.271 Y143.371 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.871 Y143.371 E0.26651
G1 X160.871 Y152.971 E0.26651
G1 X151.271 Y152.971 E0.26651
G1 X151.271 Y143.431 E0.26484
;WIPE_START
M204 S5000
G1 X151.618 Y143.571 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z3.2 F18000
;AFTER_LAYER_CHANGE
;3.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z3.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X148.978 Y140.905
; decel to extrusion
M204 S4500
G1 X146.352 Y138.252
; end travel
G1 Z3.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.506 Y138.252 E0.27308
G1 X137.506 Y129.406 E0.27308
G1 X146.352 Y129.406 E0.27308
G1 X146.352 Y138.192 E0.27123
G1 X146.729 Y138.629 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.129 Y138.629 E0.26651
G1 X137.129 Y129.029 E0.26651
G1 X146.729 Y129.029 E0.26651
G1 X146.729 Y138.569 E0.26484
;WIPE_START
M204 S5000
G1 X146.382 Y138.429 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z3.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.072 Y141.045
; decel to extrusion
M204 S4500
G1 X151.748 Y143.648
; end travel
G1 Z3.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.594 Y143.648 E0.27308
G1 X160.594 Y152.494 E0.27308
G1 X151.748 Y152.494 E0.27308
G1 X151.748 Y143.708 E0.27123
G1 X151.371 Y143.271 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X160.971 Y143.271 E0.26651
G1 X160.971 Y152.871 E0.26651
G1 X151.371 Y152.871 E0.26651
G1 X151.371 Y143.331 E0.26484
;WIPE_START
M204 S5000
G1 X151.718 Y143.471 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z3.4 F18000
;AFTER_LAYER_CHANGE
;3.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z3.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.078 Y140.805
; decel to extrusion
M204 S4500
G1 X146.452 Y138.152
; end travel
G1 Z3.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.606 Y138.152 E0.27308
G1 X137.606 Y129.306 E0.27308
G1 X146.452 Y129.306 E0.27308
G1 X146.452 Y138.092 E0.27123
G1 X146.829 Y138.529 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.229 Y138.529 E0.26651
G1 X137.229 Y128.929 E0.26651
G1 X146.829 Y128.929 E0.26651
G1 X146.829 Y138.469 E0.26484
;WIPE_START
M204 S5000
G1 X146.482 Y138.329 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z3.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.172 Y140.945
; decel to extrusion
M204 S4500
G1 X151.848 Y143.548
; end travel
G1 Z3.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.694 Y143.548 E0.27308
G1 X160.694 Y152.394 E0.27308
G1 X151.848 Y152.394 E0.27308
G1 X151.848 Y143.608 E0.27123
G1 X151.471 Y143.171 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.071 Y143.171 E0.26651
G1 X161.071 Y152.771 E0.26651
G1 X151.471 Y152.771 E0.26651
G1 X151.471 Y143.231 E0.26484
;WIPE_START
M204 S5000
G1 X151.818 Y143.371 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z3.6 F18000
;AFTER_LAYER_CHANGE
;3.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.178 Y140.705
; decel to extrusion
M204 S4500
G1 X146.552 Y138.052
; end travel
G1 Z3.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.706 Y138.052 E0.27308
G1 X137.706 Y129.206 E0.27308
G1 X146.552 Y129.206 E0.27308
G1 X146.552 Y137.992 E0.27123
G1 X146.929 Y138.429 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.329 Y138.429 E0.26651
G1 X137.329 Y128.829 E0.26651
G1 X146.929 Y128.829 E0.26651
G1 X146.929 Y138.369 E0.26484
;WIPE_START
M204 S5000
G1 X146.582 Y138.229 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.272 Y140.845
; decel to extrusion
M204 S4500
G1 X151.948 Y143.448
; end travel
G1 Z3.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.794 Y143.448 E0.27308
G1 X160.794 Y152.294 E0.27308
G1 X151.948 Y152.294 E0.27308
G1 X151.948 Y143.508 E0.27123
G1 X151.571 Y143.071 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.171 Y143.071 E0.26651
G1 X161.171 Y152.671 E0.26651
G1 X151.571 Y152.671 E0.26651
G1 X151.571 Y143.131 E0.26484
;WIPE_START
M204 S5000
G1 X151.918 Y143.271 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z3.8 F18000
;AFTER_LAYER_CHANGE
;3.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z4.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.278 Y140.605
; decel to extrusion
M204 S4500
G1 X146.652 Y137.952
; end travel
G1 Z3.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.806 Y137.952 E0.27308
G1 X137.806 Y129.106 E0.27308
G1 X146.652 Y129.106 E0.27308
G1 X146.652 Y137.892 E0.27123
G1 X147.029 Y138.329 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.429 Y138.329 E0.26651
G1 X137.429 Y128.729 E0.26651
G1 X147.029 Y128.729 E0.26651
G1 X147.029 Y138.269 E0.26484
;WIPE_START
M204 S5000
G1 X146.682 Y138.129 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z4.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.372 Y140.745
; decel to extrusion
M204 S4500
G1 X152.048 Y143.348
; end travel
G1 Z3.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.894 Y143.348 E0.27308
G1 X160.894 Y152.194 E0.27308
G1 X152.048 Y152.194 E0.27308
G1 X152.048 Y143.408 E0.27123
G1 X151.671 Y142.971 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.271 Y142.971 E0.26651
G1 X161.271 Y152.571 E0.26651
G1 X151.671 Y152.571 E0.26651
G1 X151.671 Y143.031 E0.26484
;WIPE_START
M204 S5000
G1 X152.018 Y143.171 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z4 F18000
;AFTER_LAYER_CHANGE
;4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z4.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.378 Y140.505
; decel to extrusion
M204 S4500
G1 X146.752 Y137.852
; end travel
G1 Z4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X137.906 Y137.852 E0.27308
G1 X137.906 Y129.006 E0.27308
G1 X146.752 Y129.006 E0.27308
G1 X146.752 Y137.792 E0.27123
G1 X147.129 Y138.229 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.529 Y138.229 E0.26651
G1 X137.529 Y128.629 E0.26651
G1 X147.129 Y128.629 E0.26651
G1 X147.129 Y138.169 E0.26484
;WIPE_START
M204 S5000
G1 X146.782 Y138.029 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z4.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.472 Y140.645
; decel to extrusion
M204 S4500
G1 X152.148 Y143.248
; end travel
G1 Z4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X160.994 Y143.248 E0.27308
G1 X160.994 Y152.094 E0.27308
G1 X152.148 Y152.094 E0.27308
G1 X152.148 Y143.308 E0.27123
G1 X151.771 Y142.871 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.371 Y142.871 E0.26651
G1 X161.371 Y152.471 E0.26651
G1 X151.771 Y152.471 E0.26651
G1 X151.771 Y142.931 E0.26484
;WIPE_START
M204 S5000
G1 X152.118 Y143.071 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z4.2 F18000
;AFTER_LAYER_CHANGE
;4.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z4.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.478 Y140.405
; decel to extrusion
M204 S4500
G1 X146.852 Y137.752
; end travel
G1 Z4.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.006 Y137.752 E0.27308
G1 X138.006 Y128.906 E0.27308
G1 X146.852 Y128.906 E0.27308
G1 X146.852 Y137.692 E0.27123
G1 X147.229 Y138.129 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.629 Y138.129 E0.26651
G1 X137.629 Y128.529 E0.26651
G1 X147.229 Y128.529 E0.26651
G1 X147.229 Y138.069 E0.26484
;WIPE_START
M204 S5000
G1 X146.882 Y137.929 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z4.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.572 Y140.545
; decel to extrusion
M204 S4500
G1 X152.248 Y143.148
; end travel
G1 Z4.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.094 Y143.148 E0.27308
G1 X161.094 Y151.994 E0.27308
G1 X152.248 Y151.994 E0.27308
G1 X152.248 Y143.208 E0.27123
G1 X151.871 Y142.771 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.471 Y142.771 E0.26651
G1 X161.471 Y152.371 E0.26651
G1 X151.871 Y152.371 E0.26651
G1 X151.871 Y142.831 E0.26484
;WIPE_START
M204 S5000
G1 X152.218 Y142.971 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z4.4 F18000
;AFTER_LAYER_CHANGE
;4.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z4.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.578 Y140.305
; decel to extrusion
M204 S4500
G1 X146.952 Y137.652
; end travel
G1 Z4.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.106 Y137.652 E0.27308
G1 X138.106 Y128.806 E0.27308
G1 X146.952 Y128.806 E0.27308
G1 X146.952 Y137.592 E0.27123
G1 X147.329 Y138.029 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.729 Y138.029 E0.26651
G1 X137.729 Y128.429 E0.26651
G1 X147.329 Y128.429 E0.26651
G1 X147.329 Y137.969 E0.26484
;WIPE_START
M204 S5000
G1 X146.982 Y137.829 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z4.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.672 Y140.445
; decel to extrusion
M204 S4500
G1 X152.348 Y143.048
; end travel
G1 Z4.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.194 Y143.048 E0.27308
G1 X161.194 Y151.894 E0.27308
G1 X152.348 Y151.894 E0.27308
G1 X152.348 Y143.108 E0.27123
G1 X151.971 Y142.671 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.571 Y142.671 E0.26651
G1 X161.571 Y152.271 E0.26651
G1 X151.971 Y152.271 E0.26651
G1 X151.971 Y142.731 E0.26484
;WIPE_START
M204 S5000
G1 X152.318 Y142.871 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z4.6 F18000
;AFTER_LAYER_CHANGE
;4.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z5 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.678 Y140.205
; decel to extrusion
M204 S4500
G1 X147.052 Y137.552
; end travel
G1 Z4.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.206 Y137.552 E0.27308
G1 X138.206 Y128.706 E0.27308
G1 X147.052 Y128.706 E0.27308
G1 X147.052 Y137.492 E0.27123
G1 X147.429 Y137.929 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.829 Y137.929 E0.26651
G1 X137.829 Y128.329 E0.26651
G1 X147.429 Y128.329 E0.26651
G1 X147.429 Y137.869 E0.26484
;WIPE_START
M204 S5000
G1 X147.082 Y137.729 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z5 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.772 Y140.345
; decel to extrusion
M204 S4500
G1 X152.448 Y142.948
; end travel
G1 Z4.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.294 Y142.948 E0.27308
G1 X161.294 Y151.794 E0.27308
G1 X152.448 Y151.794 E0.27308
G1 X152.448 Y143.008 E0.27123
G1 X152.071 Y142.571 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.671 Y142.571 E0.26651
G1 X161.671 Y152.171 E0.26651
G1 X152.071 Y152.171 E0.26651
G1 X152.071 Y142.631 E0.26484
;WIPE_START
M204 S5000
G1 X152.418 Y142.771 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z4.8 F18000
;AFTER_LAYER_CHANGE
;4.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z5.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.778 Y140.105
; decel to extrusion
M204 S4500
G1 X147.152 Y137.452
; end travel
G1 Z4.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.306 Y137.452 E0.27308
G1 X138.306 Y128.606 E0.27308
G1 X147.152 Y128.606 E0.27308
G1 X147.152 Y137.392 E0.27123
G1 X147.529 Y137.829 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X137.929 Y137.829 E0.26651
G1 X137.929 Y128.229 E0.26651
G1 X147.529 Y128.229 E0.26651
G1 X147.529 Y137.769 E0.26484
;WIPE_START
M204 S5000
G1 X147.182 Y137.629 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z5.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.872 Y140.245
; decel to extrusion
M204 S4500
G1 X152.548 Y142.848
; end travel
G1 Z4.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.394 Y142.848 E0.27308
G1 X161.394 Y151.694 E0.27308
G1 X152.548 Y151.694 E0.27308
G1 X152.548 Y142.908 E0.27123
G1 X152.171 Y142.471 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.771 Y142.471 E0.26651
G1 X161.771 Y152.071 E0.26651
G1 X152.171 Y152.071 E0.26651
G1 X152.171 Y142.531 E0.26484
;WIPE_START
M204 S5000
G1 X152.518 Y142.671 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z5 F18000
;AFTER_LAYER_CHANGE
;5

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z5.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.878 Y140.005
; decel to extrusion
M204 S4500
G1 X147.252 Y137.352
; end travel
G1 Z5
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.406 Y137.352 E0.27308
G1 X138.406 Y128.506 E0.27308
G1 X147.252 Y128.506 E0.27308
G1 X147.252 Y137.292 E0.27123
G1 X147.629 Y137.729 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.029 Y137.729 E0.26651
G1 X138.029 Y128.129 E0.26651
G1 X147.629 Y128.129 E0.26651
G1 X147.629 Y137.669 E0.26484
;WIPE_START
M204 S5000
G1 X147.282 Y137.529 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z5.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X149.972 Y140.145
; decel to extrusion
M204 S4500
G1 X152.648 Y142.748
; end travel
G1 Z5
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.494 Y142.748 E0.27308
G1 X161.494 Y151.594 E0.27308
G1 X152.648 Y151.594 E0.27308
G1 X152.648 Y142.808 E0.27123
G1 X152.271 Y142.371 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.871 Y142.371 E0.26651
G1 X161.871 Y151.971 E0.26651
G1 X152.271 Y151.971 E0.26651
G1 X152.271 Y142.431 E0.26484
;WIPE_START
M204 S5000
G1 X152.618 Y142.571 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:5.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z5.2 F18000
;AFTER_LAYER_CHANGE
;5.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z5.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X149.978 Y139.905
; decel to extrusion
M204 S4500
G1 X147.352 Y137.252
; end travel
G1 Z5.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.506 Y137.252 E0.27308
G1 X138.506 Y128.406 E0.27308
G1 X147.352 Y128.406 E0.27308
G1 X147.352 Y137.192 E0.27123
G1 X147.729 Y137.629 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.129 Y137.629 E0.26651
G1 X138.129 Y128.029 E0.26651
G1 X147.729 Y128.029 E0.26651
G1 X147.729 Y137.569 E0.26484
;WIPE_START
M204 S5000
G1 X147.382 Y137.429 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z5.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.072 Y140.045
; decel to extrusion
M204 S4500
G1 X152.748 Y142.648
; end travel
G1 Z5.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.594 Y142.648 E0.27308
G1 X161.594 Y151.494 E0.27308
G1 X152.748 Y151.494 E0.27308
G1 X152.748 Y142.708 E0.27123
G1 X152.371 Y142.271 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X161.971 Y142.271 E0.26651
G1 X161.971 Y151.871 E0.26651
G1 X152.371 Y151.871 E0.26651
G1 X152.371 Y142.331 E0.26484
;WIPE_START
M204 S5000
G1 X152.718 Y142.471 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:5.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z5.4 F18000
;AFTER_LAYER_CHANGE
;5.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z5.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.078 Y139.805
; decel to extrusion
M204 S4500
G1 X147.452 Y137.152
; end travel
G1 Z5.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.606 Y137.152 E0.27308
G1 X138.606 Y128.306 E0.27308
G1 X147.452 Y128.306 E0.27308
G1 X147.452 Y137.092 E0.27123
G1 X147.829 Y137.529 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.229 Y137.529 E0.26651
G1 X138.229 Y127.929 E0.26651
G1 X147.829 Y127.929 E0.26651
G1 X147.829 Y137.469 E0.26484
;WIPE_START
M204 S5000
G1 X147.482 Y137.329 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z5.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.172 Y139.945
; decel to extrusion
M204 S4500
G1 X152.848 Y142.548
; end travel
G1 Z5.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.694 Y142.548 E0.27308
G1 X161.694 Y151.394 E0.27308
G1 X152.848 Y151.394 E0.27308
G1 X152.848 Y142.608 E0.27123
G1 X152.471 Y142.171 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.071 Y142.171 E0.26651
G1 X162.071 Y151.771 E0.26651
G1 X152.471 Y151.771 E0.26651
G1 X152.471 Y142.231 E0.26484
;WIPE_START
M204 S5000
G1 X152.818 Y142.371 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:5.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z5.6 F18000
;AFTER_LAYER_CHANGE
;5.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.178 Y139.705
; decel to extrusion
M204 S4500
G1 X147.552 Y137.052
; end travel
G1 Z5.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.706 Y137.052 E0.27308
G1 X138.706 Y128.206 E0.27308
G1 X147.552 Y128.206 E0.27308
G1 X147.552 Y136.992 E0.27123
G1 X147.929 Y137.429 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.329 Y137.429 E0.26651
G1 X138.329 Y127.829 E0.26651
G1 X147.929 Y127.829 E0.26651
G1 X147.929 Y137.369 E0.26484
;WIPE_START
M204 S5000
G1 X147.582 Y137.229 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.272 Y139.845
; decel to extrusion
M204 S4500
G1 X152.948 Y142.448
; end travel
G1 Z5.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.794 Y142.448 E0.27308
G1 X161.794 Y151.294 E0.27308
G1 X152.948 Y151.294 E0.27308
G1 X152.948 Y142.508 E0.27123
G1 X152.571 Y142.071 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.171 Y142.071 E0.26651
G1 X162.171 Y151.671 E0.26651
G1 X152.571 Y151.671 E0.26651
G1 X152.571 Y142.131 E0.26484
;WIPE_START
M204 S5000
G1 X152.918 Y142.271 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:5.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z5.8 F18000
;AFTER_LAYER_CHANGE
;5.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z6.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.278 Y139.605
; decel to extrusion
M204 S4500
G1 X147.652 Y136.952
; end travel
G1 Z5.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.806 Y136.952 E0.27308
G1 X138.806 Y128.106 E0.27308
G1 X147.652 Y128.106 E0.27308
G1 X147.652 Y136.892 E0.27123
G1 X148.029 Y137.329 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.429 Y137.329 E0.26651
G1 X138.429 Y127.729 E0.26651
G1 X148.029 Y127.729 E0.26651
G1 X148.029 Y137.269 E0.26484
;WIPE_START
M204 S5000
G1 X147.682 Y137.129 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z6.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.372 Y139.745
; decel to extrusion
M204 S4500
G1 X153.048 Y142.348
; end travel
G1 Z5.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.894 Y142.348 E0.27308
G1 X161.894 Y151.194 E0.27308
G1 X153.048 Y151.194 E0.27308
G1 X153.048 Y142.408 E0.27123
G1 X152.671 Y141.971 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.271 Y141.971 E0.26651
G1 X162.271 Y151.571 E0.26651
G1 X152.671 Y151.571 E0.26651
G1 X152.671 Y142.031 E0.26484
;WIPE_START
M204 S5000
G1 X153.018 Y142.171 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z6 F18000
;AFTER_LAYER_CHANGE
;6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z6.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.378 Y139.505
; decel to extrusion
M204 S4500
G1 X147.752 Y136.852
; end travel
G1 Z6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X138.906 Y136.852 E0.27308
G1 X138.906 Y128.006 E0.27308
G1 X147.752 Y128.006 E0.27308
G1 X147.752 Y136.792 E0.27123
G1 X148.129 Y137.229 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.529 Y137.229 E0.26651
G1 X138.529 Y127.629 E0.26651
G1 X148.129 Y127.629 E0.26651
G1 X148.129 Y137.169 E0.26484
;WIPE_START
M204 S5000
G1 X147.782 Y137.029 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z6.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.472 Y139.645
; decel to extrusion
M204 S4500
G1 X153.148 Y142.248
; end travel
G1 Z6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X161.994 Y142.248 E0.27308
G1 X161.994 Y151.094 E0.27308
G1 X153.148 Y151.094 E0.27308
G1 X153.148 Y142.308 E0.27123
G1 X152.771 Y141.871 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.371 Y141.871 E0.26651
G1 X162.371 Y151.471 E0.26651
G1 X152.771 Y151.471 E0.26651
G1 X152.771 Y141.931 E0.26484
;WIPE_START
M204 S5000
G1 X153.118 Y142.071 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:6.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z6.2 F18000
;AFTER_LAYER_CHANGE
;6.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z6.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.478 Y139.405
; decel to extrusion
M204 S4500
G1 X147.852 Y136.752
; end travel
G1 Z6.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.006 Y136.752 E0.27308
G1 X139.006 Y127.906 E0.27308
G1 X147.852 Y127.906 E0.27308
G1 X147.852 Y136.692 E0.27123
G1 X148.229 Y137.129 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.629 Y137.129 E0.26651
G1 X138.629 Y127.529 E0.26651
G1 X148.229 Y127.529 E0.26651
G1 X148.229 Y137.069 E0.26484
;WIPE_START
M204 S5000
G1 X147.882 Y136.929 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z6.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.572 Y139.545
; decel to extrusion
M204 S4500
G1 X153.248 Y142.148
; end travel
G1 Z6.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.094 Y142.148 E0.27308
G1 X162.094 Y150.994 E0.27308
G1 X153.248 Y150.994 E0.27308
G1 X153.248 Y142.208 E0.27123
G1 X152.871 Y141.771 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.471 Y141.771 E0.26651
G1 X162.471 Y151.371 E0.26651
G1 X152.871 Y151.371 E0.26651
G1 X152.871 Y141.831 E0.26484
;WIPE_START
M204 S5000
G1 X153.218 Y141.971 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:6.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z6.4 F18000
;AFTER_LAYER_CHANGE
;6.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z6.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.578 Y139.305
; decel to extrusion
M204 S4500
G1 X147.952 Y136.652
; end travel
G1 Z6.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.106 Y136.652 E0.27308
G1 X139.106 Y127.806 E0.27308
G1 X147.952 Y127.806 E0.27308
G1 X147.952 Y136.592 E0.27123
G1 X148.329 Y137.029 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.729 Y137.029 E0.26651
G1 X138.729 Y127.429 E0.26651
G1 X148.329 Y127.429 E0.26651
G1 X148.329 Y136.969 E0.26484
;WIPE_START
M204 S5000
G1 X147.982 Y136.829 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z6.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.672 Y139.445
; decel to extrusion
M204 S4500
G1 X153.348 Y142.048
; end travel
G1 Z6.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.194 Y142.048 E0.27308
G1 X162.194 Y150.894 E0.27308
G1 X153.348 Y150.894 E0.27308
G1 X153.348 Y142.108 E0.27123
G1 X152.971 Y141.671 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.571 Y141.671 E0.26651
G1 X162.571 Y151.271 E0.26651
G1 X152.971 Y151.271 E0.26651
G1 X152.971 Y141.731 E0.26484
;WIPE_START
M204 S5000
G1 X153.318 Y141.871 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:6.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z6.6 F18000
;AFTER_LAYER_CHANGE
;6.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z7 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.678 Y139.205
; decel to extrusion
M204 S4500
G1 X148.052 Y136.552
; end travel
G1 Z6.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.206 Y136.552 E0.27308
G1 X139.206 Y127.706 E0.27308
G1 X148.052 Y127.706 E0.27308
G1 X148.052 Y136.492 E0.27123
G1 X148.429 Y136.929 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.829 Y136.929 E0.26651
G1 X138.829 Y127.329 E0.26651
G1 X148.429 Y127.329 E0.26651
G1 X148.429 Y136.869 E0.26484
;WIPE_START
M204 S5000
G1 X148.082 Y136.729 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z7 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.772 Y139.345
; decel to extrusion
M204 S4500
G1 X153.448 Y141.948
; end travel
G1 Z6.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.294 Y141.948 E0.27308
G1 X162.294 Y150.794 E0.27308
G1 X153.448 Y150.794 E0.27308
G1 X153.448 Y142.008 E0.27123
G1 X153.071 Y141.571 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.671 Y141.571 E0.26651
G1 X162.671 Y151.171 E0.26651
G1 X153.071 Y151.171 E0.26651
G1 X153.071 Y141.631 E0.26484
;WIPE_START
M204 S5000
G1 X153.418 Y141.771 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:6.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z6.8 F18000
;AFTER_LAYER_CHANGE
;6.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z7.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.778 Y139.105
; decel to extrusion
M204 S4500
G1 X148.152 Y136.452
; end travel
G1 Z6.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.306 Y136.452 E0.27308
G1 X139.306 Y127.606 E0.27308
G1 X148.152 Y127.606 E0.27308
G1 X148.152 Y136.392 E0.27123
G1 X148.529 Y136.829 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X138.929 Y136.829 E0.26651
G1 X138.929 Y127.229 E0.26651
G1 X148.529 Y127.229 E0.26651
G1 X148.529 Y136.769 E0.26484
;WIPE_START
M204 S5000
G1 X148.182 Y136.629 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z7.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.872 Y139.245
; decel to extrusion
M204 S4500
G1 X153.548 Y141.848
; end travel
G1 Z6.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.394 Y141.848 E0.27308
G1 X162.394 Y150.694 E0.27308
G1 X153.548 Y150.694 E0.27308
G1 X153.548 Y141.908 E0.27123
G1 X153.171 Y141.471 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.771 Y141.471 E0.26651
G1 X162.771 Y151.071 E0.26651
G1 X153.171 Y151.071 E0.26651
G1 X153.171 Y141.531 E0.26484
;WIPE_START
M204 S5000
G1 X153.518 Y141.671 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:7
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z7 F18000
;AFTER_LAYER_CHANGE
;7

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z7.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.878 Y139.005
; decel to extrusion
M204 S4500
G1 X148.252 Y136.352
; end travel
G1 Z7
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.406 Y136.352 E0.27308
G1 X139.406 Y127.506 E0.27308
G1 X148.252 Y127.506 E0.27308
G1 X148.252 Y136.292 E0.27123
G1 X148.629 Y136.729 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.029 Y136.729 E0.26651
G1 X139.029 Y127.129 E0.26651
G1 X148.629 Y127.129 E0.26651
G1 X148.629 Y136.669 E0.26484
;WIPE_START
M204 S5000
G1 X148.282 Y136.529 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z7.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X150.972 Y139.145
; decel to extrusion
M204 S4500
G1 X153.648 Y141.748
; end travel
G1 Z7
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.494 Y141.748 E0.27308
G1 X162.494 Y150.594 E0.27308
G1 X153.648 Y150.594 E0.27308
G1 X153.648 Y141.808 E0.27123
G1 X153.271 Y141.371 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.871 Y141.371 E0.26651
G1 X162.871 Y150.971 E0.26651
G1 X153.271 Y150.971 E0.26651
G1 X153.271 Y141.431 E0.26484
;WIPE_START
M204 S5000
G1 X153.618 Y141.571 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:7.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z7.2 F18000
;AFTER_LAYER_CHANGE
;7.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z7.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X150.978 Y138.905
; decel to extrusion
M204 S4500
G1 X148.352 Y136.252
; end travel
G1 Z7.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.506 Y136.252 E0.27308
G1 X139.506 Y127.406 E0.27308
G1 X148.352 Y127.406 E0.27308
G1 X148.352 Y136.192 E0.27123
G1 X148.729 Y136.629 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.129 Y136.629 E0.26651
G1 X139.129 Y127.029 E0.26651
G1 X148.729 Y127.029 E0.26651
G1 X148.729 Y136.569 E0.26484
;WIPE_START
M204 S5000
G1 X148.382 Y136.429 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z7.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.072 Y139.045
; decel to extrusion
M204 S4500
G1 X153.748 Y141.648
; end travel
G1 Z7.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.594 Y141.648 E0.27308
G1 X162.594 Y150.494 E0.27308
G1 X153.748 Y150.494 E0.27308
G1 X153.748 Y141.708 E0.27123
G1 X153.371 Y141.271 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X162.971 Y141.271 E0.26651
G1 X162.971 Y150.871 E0.26651
G1 X153.371 Y150.871 E0.26651
G1 X153.371 Y141.331 E0.26484
;WIPE_START
M204 S5000
G1 X153.718 Y141.471 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:7.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z7.4 F18000
;AFTER_LAYER_CHANGE
;7.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z7.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.078 Y138.805
; decel to extrusion
M204 S4500
G1 X148.452 Y136.152
; end travel
G1 Z7.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.606 Y136.152 E0.27308
G1 X139.606 Y127.306 E0.27308
G1 X148.452 Y127.306 E0.27308
G1 X148.452 Y136.092 E0.27123
G1 X148.829 Y136.529 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.229 Y136.529 E0.26651
G1 X139.229 Y126.929 E0.26651
G1 X148.829 Y126.929 E0.26651
G1 X148.829 Y136.469 E0.26484
;WIPE_START
M204 S5000
G1 X148.482 Y136.329 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z7.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.172 Y138.945
; decel to extrusion
M204 S4500
G1 X153.848 Y141.548
; end travel
G1 Z7.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.694 Y141.548 E0.27308
G1 X162.694 Y150.394 E0.27308
G1 X153.848 Y150.394 E0.27308
G1 X153.848 Y141.608 E0.27123
G1 X153.471 Y141.171 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.071 Y141.171 E0.26651
G1 X163.071 Y150.771 E0.26651
G1 X153.471 Y150.771 E0.26651
G1 X153.471 Y141.231 E0.26484
;WIPE_START
M204 S5000
G1 X153.818 Y141.371 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:7.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z7.6 F18000
;AFTER_LAYER_CHANGE
;7.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.178 Y138.705
; decel to extrusion
M204 S4500
G1 X148.552 Y136.052
; end travel
G1 Z7.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.706 Y136.052 E0.27308
G1 X139.706 Y127.206 E0.27308
G1 X148.552 Y127.206 E0.27308
G1 X148.552 Y135.992 E0.27123
G1 X148.929 Y136.429 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.329 Y136.429 E0.26651
G1 X139.329 Y126.829 E0.26651
G1 X148.929 Y126.829 E0.26651
G1 X148.929 Y136.369 E0.26484
;WIPE_START
M204 S5000
G1 X148.582 Y136.229 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.272 Y138.845
; decel to extrusion
M204 S4500
G1 X153.948 Y141.448
; end travel
G1 Z7.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.794 Y141.448 E0.27308
G1 X162.794 Y150.294 E0.27308
G1 X153.948 Y150.294 E0.27308
G1 X153.948 Y141.508 E0.27123
G1 X153.571 Y141.071 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.171 Y141.071 E0.26651
G1 X163.171 Y150.671 E0.26651
G1 X153.571 Y150.671 E0.26651
G1 X153.571 Y141.131 E0.26484
;WIPE_START
M204 S5000
G1 X153.918 Y141.271 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:7.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z7.8 F18000
;AFTER_LAYER_CHANGE
;7.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z8.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.278 Y138.605
; decel to extrusion
M204 S4500
G1 X148.652 Y135.952
; end travel
G1 Z7.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.806 Y135.952 E0.27308
G1 X139.806 Y127.106 E0.27308
G1 X148.652 Y127.106 E0.27308
G1 X148.652 Y135.892 E0.27123
G1 X149.029 Y136.329 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.429 Y136.329 E0.26651
G1 X139.429 Y126.729 E0.26651
G1 X149.029 Y126.729 E0.26651
G1 X149.029 Y136.269 E0.26484
;WIPE_START
M204 S5000
G1 X148.682 Y136.129 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z8.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.372 Y138.745
; decel to extrusion
M204 S4500
G1 X154.048 Y141.348
; end travel
G1 Z7.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.894 Y141.348 E0.27308
G1 X162.894 Y150.194 E0.27308
G1 X154.048 Y150.194 E0.27308
G1 X154.048 Y141.408 E0.27123
G1 X153.671 Y140.971 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.271 Y140.971 E0.26651
G1 X163.271 Y150.571 E0.26651
G1 X153.671 Y150.571 E0.26651
G1 X153.671 Y141.031 E0.26484
;WIPE_START
M204 S5000
G1 X154.018 Y141.171 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z8 F18000
;AFTER_LAYER_CHANGE
;8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z8.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.378 Y138.505
; decel to extrusion
M204 S4500
G1 X148.752 Y135.852
; end travel
G1 Z8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X139.906 Y135.852 E0.27308
G1 X139.906 Y127.006 E0.27308
G1 X148.752 Y127.006 E0.27308
G1 X148.752 Y135.792 E0.27123
G1 X149.129 Y136.229 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.529 Y136.229 E0.26651
G1 X139.529 Y126.629 E0.26651
G1 X149.129 Y126.629 E0.26651
G1 X149.129 Y136.169 E0.26484
;WIPE_START
M204 S5000
G1 X148.782 Y136.029 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z8.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.472 Y138.645
; decel to extrusion
M204 S4500
G1 X154.148 Y141.248
; end travel
G1 Z8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X162.994 Y141.248 E0.27308
G1 X162.994 Y150.094 E0.27308
G1 X154.148 Y150.094 E0.27308
G1 X154.148 Y141.308 E0.27123
G1 X153.771 Y140.871 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.371 Y140.871 E0.26651
G1 X163.371 Y150.471 E0.26651
G1 X153.771 Y150.471 E0.26651
G1 X153.771 Y140.931 E0.26484
;WIPE_START
M204 S5000
G1 X154.118 Y141.071 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:8.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z8.2 F18000
;AFTER_LAYER_CHANGE
;8.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z8.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.478 Y138.405
; decel to extrusion
M204 S4500
G1 X148.852 Y135.752
; end travel
G1 Z8.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.006 Y135.752 E0.27308
G1 X140.006 Y126.906 E0.27308
G1 X148.852 Y126.906 E0.27308
G1 X148.852 Y135.692 E0.27123
G1 X149.229 Y136.129 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.629 Y136.129 E0.26651
G1 X139.629 Y126.529 E0.26651
G1 X149.229 Y126.529 E0.26651
G1 X149.229 Y136.069 E0.26484
;WIPE_START
M204 S5000
G1 X148.882 Y135.929 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z8.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.572 Y138.545
; decel to extrusion
M204 S4500
G1 X154.248 Y141.148
; end travel
G1 Z8.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.094 Y141.148 E0.27308
G1 X163.094 Y149.994 E0.27308
G1 X154.248 Y149.994 E0.27308
G1 X154.248 Y141.208 E0.27123
G1 X153.871 Y140.771 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.471 Y140.771 E0.26651
G1 X163.471 Y150.371 E0.26651
G1 X153.871 Y150.371 E0.26651
G1 X153.871 Y140.831 E0.26484
;WIPE_START
M204 S5000
G1 X154.218 Y140.971 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:8.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z8.4 F18000
;AFTER_LAYER_CHANGE
;8.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z8.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.578 Y138.305
; decel to extrusion
M204 S4500
G1 X148.952 Y135.652
; end travel
G1 Z8.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.106 Y135.652 E0.27308
G1 X140.106 Y126.806 E0.27308
G1 X148.952 Y126.806 E0.27308
G1 X148.952 Y135.592 E0.27123
G1 X149.329 Y136.029 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.729 Y136.029 E0.26651
G1 X139.729 Y126.429 E0.26651
G1 X149.329 Y126.429 E0.26651
G1 X149.329 Y135.969 E0.26484
;WIPE_START
M204 S5000
G1 X148.982 Y135.829 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z8.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.672 Y138.445
; decel to extrusion
M204 S4500
G1 X154.348 Y141.048
; end travel
G1 Z8.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.194 Y141.048 E0.27308
G1 X163.194 Y149.894 E0.27308
G1 X154.348 Y149.894 E0.27308
G1 X154.348 Y141.108 E0.27123
G1 X153.971 Y140.671 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.571 Y140.671 E0.26651
G1 X163.571 Y150.271 E0.26651
G1 X153.971 Y150.271 E0.26651
G1 X153.971 Y140.731 E0.26484
;WIPE_START
M204 S5000
G1 X154.318 Y140.871 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:8.6
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
;8.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z8.6 F18000
;AFTER_LAYER_CHANGE
;8.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z9 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.678 Y138.205
; decel to extrusion
M204 S4500
G1 X149.052 Y135.552
; end travel
G1 Z8.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.206 Y135.552 E0.27308
G1 X140.206 Y126.706 E0.27308
G1 X149.052 Y126.706 E0.27308
G1 X149.052 Y135.492 E0.27123
G1 X149.429 Y135.929 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.829 Y135.929 E0.26651
G1 X139.829 Y126.329 E0.26651
G1 X149.429 Y126.329 E0.26651
G1 X149.429 Y135.869 E0.26484
;WIPE_START
M204 S5000
G1 X149.082 Y135.729 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z9 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.772 Y138.345
; decel to extrusion
M204 S4500
G1 X154.448 Y140.948
; end travel
G1 Z8.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.294 Y140.948 E0.27308
G1 X163.294 Y149.794 E0.27308
G1 X154.448 Y149.794 E0.27308
G1 X154.448 Y141.008 E0.27123
G1 X154.071 Y140.571 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.671 Y140.571 E0.26651
G1 X163.671 Y150.171 E0.26651
G1 X154.071 Y150.171 E0.26651
G1 X154.071 Y140.631 E0.26484
;WIPE_START
M204 S5000
G1 X154.418 Y140.771 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:8.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z8.8 F18000
;AFTER_LAYER_CHANGE
;8.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z9.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.778 Y138.105
; decel to extrusion
M204 S4500
G1 X149.152 Y135.452
; end travel
G1 Z8.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.306 Y135.452 E0.27308
G1 X140.306 Y126.606 E0.27308
G1 X149.152 Y126.606 E0.27308
G1 X149.152 Y135.392 E0.27123
G1 X149.529 Y135.829 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X139.929 Y135.829 E0.26651
G1 X139.929 Y126.229 E0.26651
G1 X149.529 Y126.229 E0.26651
G1 X149.529 Y135.769 E0.26484
;WIPE_START
M204 S5000
G1 X149.182 Y135.629 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z9.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.872 Y138.245
; decel to extrusion
M204 S4500
G1 X154.548 Y140.848
; end travel
G1 Z8.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.394 Y140.848 E0.27308
G1 X163.394 Y149.694 E0.27308
G1 X154.548 Y149.694 E0.27308
G1 X154.548 Y140.908 E0.27123
G1 X154.171 Y140.471 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.771 Y140.471 E0.26651
G1 X163.771 Y150.071 E0.26651
G1 X154.171 Y150.071 E0.26651
G1 X154.171 Y140.531 E0.26484
;WIPE_START
M204 S5000
G1 X154.518 Y140.671 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:9
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z9 F18000
;AFTER_LAYER_CHANGE
;9

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z9.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.878 Y138.005
; decel to extrusion
M204 S4500
G1 X149.252 Y135.352
; end travel
G1 Z9
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.406 Y135.352 E0.27308
G1 X140.406 Y126.506 E0.27308
G1 X149.252 Y126.506 E0.27308
G1 X149.252 Y135.292 E0.27123
G1 X149.629 Y135.729 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X140.029 Y135.729 E0.26651
G1 X140.029 Y126.129 E0.26651
G1 X149.629 Y126.129 E0.26651
G1 X149.629 Y135.669 E0.26484
;WIPE_START
M204 S5000
G1 X149.282 Y135.529 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z9.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X151.972 Y138.145
; decel to extrusion
M204 S4500
G1 X154.648 Y140.748
; end travel
G1 Z9
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.494 Y140.748 E0.27308
G1 X163.494 Y149.594 E0.27308
G1 X154.648 Y149.594 E0.27308
G1 X154.648 Y140.808 E0.27123
G1 X154.271 Y140.371 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.871 Y140.371 E0.26651
G1 X163.871 Y149.971 E0.26651
G1 X154.271 Y149.971 E0.26651
G1 X154.271 Y140.431 E0.26484
;WIPE_START
M204 S5000
G1 X154.618 Y140.571 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:9.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.2

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z9.2 F18000
;AFTER_LAYER_CHANGE
;9.2

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z9.6 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X151.978 Y137.905
; decel to extrusion
M204 S4500
G1 X149.352 Y135.252
; end travel
G1 Z9.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.506 Y135.252 E0.27308
G1 X140.506 Y126.406 E0.27308
G1 X149.352 Y126.406 E0.27308
G1 X149.352 Y135.192 E0.27123
G1 X149.729 Y135.629 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X140.129 Y135.629 E0.26651
G1 X140.129 Y126.029 E0.26651
G1 X149.729 Y126.029 E0.26651
G1 X149.729 Y135.569 E0.26484
;WIPE_START
M204 S5000
G1 X149.382 Y135.429 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z9.6 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X152.072 Y138.045
; decel to extrusion
M204 S4500
G1 X154.748 Y140.648
; end travel
G1 Z9.2
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.594 Y140.648 E0.27308
G1 X163.594 Y149.494 E0.27308
G1 X154.748 Y149.494 E0.27308
G1 X154.748 Y140.708 E0.27123
G1 X154.371 Y140.271 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X163.971 Y140.271 E0.26651
G1 X163.971 Y149.871 E0.26651
G1 X154.371 Y149.871 E0.26651
G1 X154.371 Y140.331 E0.26484
;WIPE_START
M204 S5000
G1 X154.718 Y140.471 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:9.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.4

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z9.4 F18000
;AFTER_LAYER_CHANGE
;9.4

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z9.8 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X152.078 Y137.805
; decel to extrusion
M204 S4500
G1 X149.452 Y135.152
; end travel
G1 Z9.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.606 Y135.152 E0.27308
G1 X140.606 Y126.306 E0.27308
G1 X149.452 Y126.306 E0.27308
G1 X149.452 Y135.092 E0.27123
G1 X149.829 Y135.529 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X140.229 Y135.529 E0.26651
G1 X140.229 Y125.929 E0.26651
G1 X149.829 Y125.929 E0.26651
G1 X149.829 Y135.469 E0.26484
;WIPE_START
M204 S5000
G1 X149.482 Y135.329 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z9.8 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X152.172 Y137.945
; decel to extrusion
M204 S4500
G1 X154.848 Y140.548
; end travel
G1 Z9.4
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.694 Y140.548 E0.27308
G1 X163.694 Y149.394 E0.27308
G1 X154.848 Y149.394 E0.27308
G1 X154.848 Y140.608 E0.27123
G1 X154.471 Y140.171 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X164.071 Y140.171 E0.26651
G1 X164.071 Y149.771 E0.26651
G1 X154.471 Y149.771 E0.26651
G1 X154.471 Y140.231 E0.26484
;WIPE_START
M204 S5000
G1 X154.818 Y140.371 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:9.6
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
;9.6

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z9.6 F18000
;AFTER_LAYER_CHANGE
;9.6

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z10 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X152.178 Y137.705
; decel to extrusion
M204 S4500
G1 X149.552 Y135.052
; end travel
G1 Z9.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.706 Y135.052 E0.27308
G1 X140.706 Y126.206 E0.27308
G1 X149.552 Y126.206 E0.27308
G1 X149.552 Y134.992 E0.27123
G1 X149.929 Y135.429 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X140.329 Y135.429 E0.26651
G1 X140.329 Y125.829 E0.26651
G1 X149.929 Y125.829 E0.26651
G1 X149.929 Y135.369 E0.26484
;WIPE_START
M204 S5000
G1 X149.582 Y135.229 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z10 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X152.272 Y137.845
; decel to extrusion
M204 S4500
G1 X154.948 Y140.448
; end travel
G1 Z9.6
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.794 Y140.448 E0.27308
G1 X163.794 Y149.294 E0.27308
G1 X154.948 Y149.294 E0.27308
G1 X154.948 Y140.508 E0.27123
G1 X154.571 Y140.071 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X164.171 Y140.071 E0.26651
G1 X164.171 Y149.671 E0.26651
G1 X154.571 Y149.671 E0.26651
G1 X154.571 Y140.131 E0.26484
;WIPE_START
M204 S5000
G1 X154.918 Y140.271 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:9.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.8

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z9.8 F18000
;AFTER_LAYER_CHANGE
;9.8

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z10.2 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X152.278 Y137.605
; decel to extrusion
M204 S4500
G1 X149.652 Y134.952
; end travel
G1 Z9.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X140.806 Y134.952 E0.27308
G1 X140.806 Y126.106 E0.27308
G1 X149.652 Y126.106 E0.27308
G1 X149.652 Y134.892 E0.27123
G1 X150.029 Y135.329 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X140.429 Y135.329 E0.26651
G1 X140.429 Y125.729 E0.26651
G1 X150.029 Y125.729 E0.26651
G1 X150.029 Y135.269 E0.26484
;WIPE_START
M204 S5000
G1 X149.682 Y135.129 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z10.2 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X152.372 Y137.745
; decel to extrusion
M204 S4500
G1 X155.048 Y140.348
; end travel
G1 Z9.8
G1 E0.75 F1800
;TYPE:Internal perimeter
;WIDTH:0.44
G1 F900
G1 X163.894 Y140.348 E0.27308
G1 X163.894 Y149.194 E0.27308
G1 X155.048 Y149.194 E0.27308
G1 X155.048 Y140.408 E0.27123
G1 X154.671 Y139.971 F18000
;TYPE:External perimeter
;WIDTH:0.4
G1 F900
G1 X164.271 Y139.971 E0.26651
G1 X164.271 Y149.571 E0.26651
G1 X154.671 Y149.571 E0.26651
G1 X154.671 Y140.031 E0.26484
;WIPE_START
M204 S5000
G1 X155.018 Y140.171 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
;LAYER_CHANGE
;Z:10
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;10

; stop printing object tapered_cube.stl id:0 copy 1
G1 Z10 F18000
;AFTER_LAYER_CHANGE
;10

TIMELAPSE_TAKE_FRAME
G92 E0
; INIT printing object tapered_cube.stl id:0 copy 0
G1 E-0.75 F3000
G1 Z10.4 F18000
; printing object tapered_cube.stl id:0 copy 0
; acceleration to travel
G1 X152.445 Y137.57
; decel to extrusion
M204 S4500
G1 X150.129 Y135.229
; end travel
G1 Z10
G1 E0.75 F1800
G1 F900
G1 X140.529 Y135.229 E0.26651
G1 X140.529 Y125.629 E0.26651
G1 X150.129 Y125.629 E0.26651
G1 X150.129 Y135.169 E0.26484
;WIPE_START
M204 S5000
G1 X149.782 Y135.029 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 0
; INIT printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z10.4 F18000
; stop printing object tapered_cube.stl id:0 copy 0
; printing object tapered_cube.stl id:0 copy 1
; acceleration to travel
G1 X152.408 Y137.577
; decel to extrusion
M204 S4500
G1 X154.771 Y139.871
; end travel
G1 Z10
G1 E0.75 F1800
G1 F900
G1 X164.371 Y139.871 E0.26651
G1 X164.371 Y149.471 E0.26651
G1 X154.771 Y149.471 E0.26651
G1 X154.771 Y139.931 E0.26484
;WIPE_START
M204 S5000
G1 X155.118 Y140.071 F18000
;WIPE_END
; INIT stop printing object tapered_cube.stl id:0 copy 1
G1 E-0.75 F3000
G1 Z10.4 F18000
; stop printing object tapered_cube.stl id:0 copy 1
M107
;TYPE:Custom
print_end    ;end script from macro
